### ISSUE TITLE
Disallow Extremely Small Sample Sizes

### ISSUE THREAD

**Issue by bheisler** [bheisler/criterion.rs#186]
Much of the statistics work that Criterion.rs does breaks down when sample sizes are very small - eg. <10. I'm inclined to simply disallow this configuration, but that would be a breaking change so it will have to wait for 0.3. This is the cause of #171 - the T-test bootstrapping code can produce `+-inf` values when the sample size is very small, while downstream code expects finite numbers.

If there is demand for it, perhaps Criterion.rs could switch to a different mode in this case. The only real use case for such a small sample size is when the benchmark iteration time is long - eg >100ms/iteration. That seems like a lot of work for a very niche use case though, especially since users with such benchmarks always have the option of reducing the scope of their benchmarks or  just tolerating a longer benchmarking time.

**Comment by KillTheMule** [comment]
To put in my 2 cents: My most important benchmarks are the longest ones, because they measure the "full time" the relevant operations take, rather than just parts of it. Just a moment ago I dealt with a case where the benchmark would be running for half an hour, which is quite impractical when wanting to compare things (i.e. having to run the same benchmark twice).

I'm also very fond of the long benchmark runs, because they're much closer to the real-world scenario I'm interested in than the shorter ones (i.e. in the real world, the files I have to work with just _are_ in the 200-500MB range, not 1-2MB, and I definitely want to optimize my program for the  larger file sizes; it's pretty relevant, too, since a lot of the involved timings change quite a bit when the file size changes: linearly searching a `Vec` of 100k elements might be acceptable when the tradeoff is easy modification of elements, compared to, say, a `BTreeHashMap`, but the tradeoff might be different when the number of elements gets to the 10M range).

Ok, you probably knew all that :) All I'm saying is, I'd be grateful if a way was kept to reduce the sample size for longer-running benchmarks. Thanks for ~~listening~~ reading, and thanks for criterion!

**Comment by bheisler** [comment]
Yeah, I definitely intend to allow the user to reduce the sample size. However, some of the statistical methods don't work as well if the sample size is too small.

Out of curiosity, what sample sizes are you running?

Come to think of it, adding a long-benchmark feature would be an interesting way to test out the ideas I had for custom measurements/analyses/reports. No promises though.

**Comment by KillTheMule** [comment]
> Out of curiosity, what sample sizes are you running?

For the large file I reduced the `sample_size` to 3, but felt that was a tad on the low side. It reduced the benchmark time by a lot more than 70%, so I'm actually not sure what experiments are really done after all.
