### ISSUE TITLE
Update to latest `rand` crate

### ISSUE THREAD

**Issue by bheisler** [bheisler/criterion.rs#244]
`rand` has had a couple of breaking-change releases since 0.4 (which is what Criterion.rs currently uses). We can't currently update because those versions can't be built on older versions of Rust, but we should update that in the next breaking-change release.

**Comment by Mike-Neto** [comment]
This issue seems to be fixed already
`cat Cargo.lock | grep rand`

returns 
 "rand 0.4.3 (registry+https://github.com/rust-lang/crates.io-index)",
 "rand 0.4.3 (registry+https://github.com/rust-lang/crates.io-index)",
 "rand 0.4.3 (registry+https://github.com/rust-lang/crates.io-index)",
name = "rand"
 "rand 0.4.3 (registry+https://github.com/rust-lang/crates.io-index)",
"checksum rand 0.4.3 (registry+https://github.com/rust-lang/crates.io-index)" = "8356f47b32624fef5b3301c1be97e5944ecdd595409cc5da11d05f211db6cfbd"


Which seems to be the point of this issue.
