### ISSUE TITLE
panicking gnuplot version parsing leads to unusable criterion

### ISSUE THREAD

**Issue by birkenfeld** [bheisler/criterion.rs#245]
My gnuplot identifies as
```
gnuplot 5.2 patchlevel 5a (Gentoo revision r0)
```
which obviously panics in `criterion_plot::version` and I can't use criterion with default features.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs, and thanks for the bug report!

Yeah, that's definitely a bug. In the meantime, as a workaround, you could disable Criterion.rs' default features ([see the Cargo documentation](https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section)) to disable the charts. That way, it won't call the panicking function and you should be able to carry on benchmarking.

The panicking should be fixed in the latest Git version, but it will still fail to parse and so it won't enable generating charts. I'll fix that, but it might be a while (days or weeks) before the next Criterion.rs release.

**Comment by birkenfeld** [comment]
Nice, thanks!
