### ISSUE TITLE
Remove external-program benchmarks

### ISSUE THREAD

**Issue by bheisler** [bheisler/criterion.rs#252]
External-program benchmarks never really gained much traction (why would someone use Criterion.rs to benchmark code written in some other language? Why not use a benchmarking library native to that language?) and they get in the way of adding features like custom measurements. The low usage doesn't seem to justify the maintenance burden, so I intend to deprecate this feature in 0.2.6 and delete it in 0.3.0.

**Comment by liamcurry** [comment]
I'm working on a Rust crate that has a competing C++ library and I'm using this feature to compare performance.

Since this is being depreciated, would it be possible to self-report elapsed time?

I imagine the signature could be the same as `bench_function` except `F` returns a `std::time::Duration`:

```rust
pub fn bench_self_reporting_function<F>(
    &mut self,
    id: &str,
    f: F
) -> &mut Criterion
where
    F: FnMut(&mut Bencher) -> Duration + 'static,
{
    // ...
}

// bench_self_reporting_functions
// bench_self_reporting_function_over_inputs
```

Then it should still be possible to bench external programs, without the maintenance burden.

**Comment by bheisler** [comment]
Hey, thanks for letting me know. I think you're the only person I'm aware of who's using this feature. It's likely that you could accomplish the same goal with the custom-measurements feature that I'm planning for 0.3.0; I'll try to keep this use case in mind when I'm designing that.
