### ISSUE TITLE
Guide Needs a Rework

### ISSUE THREAD

**Issue by PrismaPhonic** [bheisler/criterion.rs#256]
Hi guys,

It seems like you have a great crate here but for the life of me I can't figure out how to compare two functions.  I've read the guide on this and it's not very clear.  The code (in the guide) is just written in these vague code blocks that don't describe if all this code is supposed to live inside the `criterion_benchmark` function or sit out in the open.  I also can't seem to understand for the life of me how I would compare two functions that take multiple inputs.  Supposedly `i` in the example is the input to the Fibonacci function but what about if our functions takes different kinds of inputs (like comparing a function that takes a reference of an immutable vector against a function that takes a mutable vector - same vector contents just that one mutates the vector whereas the other just iterates over the vector).  

I think a re-write of the section on comparing functions would be very helpful

**Comment by bheisler** [comment]
Hey, thanks for the suggestion and thanks for your patience. That section of the guide does need a re-work. If nothing else, it should recommend the newer `Benchmark` structure rather than `bench_functions`.

Aside from that, I'm not sure I understand what you're trying to accomplish here - do you have a more-detailed example? In general, it probably doesn't make sense to compare two functions that take differently-typed parameters (would any comparison even be meaningful?). In this case, perhaps it does. If you're mutating the vector, however, you will need to generate a new vector for each iteration of the benchmark. I would suggest something like this:

```rust
c.bench("my_group", BenchmarkDefinition::new("my_func_1", |b| {
    let my_vector = generate_vector();
    b.iter(move || my_func_1(&my_vector));
})
.with_function("my_func_2", |b| {
    b.iter_with_setup(|| generate_vector(), |my_vector| my_func_2(&mut my_vector));
});
```

Note that I'm just writing this from memory, it might not compile without some changes, but I hope you get the idea. Since you'll be generating a new vector for every iteration of the benchmark for the mutating function, I'd suggest that however you generate your vector, it should be reasonably quick.
