### ISSUE TITLE
`iter_with_setup` measures 20ns to do nothing

### ISSUE THREAD

**Issue by LukasKalbertodt** [bheisler/criterion.rs#258]
Given this code:

```rust
fn foo(c: &mut Criterion) {
    c.bench_function("foo", |b| {
        b.iter_with_setup(
            || (),
            |_| {},
        );
    });
}
```

Running this code with criterion 0.2.7 on my notebook via `cargo bench` outputs:

```
foo                     time:   [20.022 ns 20.216 ns 20.427 ns]                 
```

What's going on here? I know that CPU timers are not infinitely precise, but 20ns seems like a whole lot of time. In particular, when replacing `b.iter_with_setup(...)` with `b.iter(|| {})` gives a more reasonable output:

```
foo                     time:   [295.95 ps 300.02 ps 304.86 ps]
```

Am I doing something wrong or is there something wrong with `iter_with_setup`?

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs!

No, you're not doing anything wrong. `iter_with_setup`'s timing model includes a lot of calls to `Instant::now` that `iter` doesn't need, so that tends to skew the results a bit. The timing functions each document their timing models so you can make an informed choice regarding which one to use.

If the time for the function you're benchmarking is large relative to the time for `Instant::now` then there's no problem. If your function is faster than that, your results can get lost in the measurement noise so it might be necessary to use `iter` instead.

Hope this helps.

**Comment by LukasKalbertodt** [comment]
Thanks for your quick answer!

I was a bit surprised by what you said and spent the last two hours trying to figure out how time works. In particular, how Rust's libstd, libc and x86 handle time. Very interesting! But also a bit disappointing, as I somehow imagined the high precision timers to be more precise and have a higher frequency. I tried to measure "doing nothing" with different methods to see how I could get the smallest duration (since the "real" duration is 0, the smaller the better). But regardless how I did it, I never got below 20ns between measurements. I tried:
- `std::time::Instant::now()`
- `libc::clock_gettime(CLOCK_MONOTONIC)`
- [`clocksource`](https://crates.io/crates/clocksource)
- [`quanta`](https://crates.io/crates/quanta)

So I learned that today, so that's good.

And sure, now it makes absolutely sense why criterion can't do better with the timing loop as specified. I know that there is still `iter_with_large_setup`, but this seems like a really extreme option (that doesn't work in many cases as the memory requirements are too high). So in my specific case, it would be useful if criterion would prepare like 100 or 1000 inputs at a time, then run the routine 100 or 1000 times and then repeat. It would greatly improve accuracy and wouldn't require a lot of memory. Do you think this is a potential API addition? I mean you can also tell the user to do that work themselves, aka: just prepare 100 time the input and do 100 times the work. I'd be just curious to know if something like this has been considered already.

In any case: thanks a lot for helping me!

**Comment by Eh2406** [comment]
criterion already does that kind of thing. As I understand it it runs your function `X = time(1100 times)` and `Y = time(100 times)` and reports `(X - Y)/1000`, with lots of smarts to pick good numbers for the constants. Your case is pathological because it is optimized out, and ... I think, `iter_with_setup` may not support this functionality... sorry for the noize...

**Comment by bheisler** [comment]
That's how `iter` works, yes. `iter_with_setup` needs to exclude the setup time on each iteration so it measures each iteration separately.

**Comment by Eh2406** [comment]
Could we add a line to `iter_with_setup` to make it clear that it has lower precision then `iter`, and that its uncertainty can not be smaller then `~20ns`? Or even better have it print a warning if `iter_with_setup` is used to estimate a time let then `~20ns`?

**Comment by LukasKalbertodt** [comment]
I think adding this info to the documentation explicitly is a good idea! For people who already know how (not) precise timing is, the timing loop in the docs already tells them that `iter_with_setup` is not going to work for tiny measurements. But it would be nice to have this info in more easy to understand words in the docs. 

But that begs the question: what is the recommended way to measure these things (this should be mentioned in the docs)? For example, what if we want to measure `Vec::push` but without allocation? I would have written this: 

```
b.iter_with_setup(
    || Vec::with_capacity(1), 
    |mut v| { v.push(3); v },
)
```

But those timings won't be precise. So how would we go about it? Should the user prepare 100 `Vec::with_capacity(1)` and then push 100 times in the second closure? Or should the user somehow try to make it work with `iter()`? I'm curious to see what you think is the best option in this situation.

**Comment by bheisler** [comment]
There isn't a great solution to this, really. What you want - a measurement function that pre-generates some input values, then times the function being applied to each element of the list to reduce measurement overhead - is reasonable. If I do that, though, Criterion.rs ends up with a whole bunch of slightly-different measurement functions without clear guidance on which one is appropriate for any given situation.

This will take some careful design to get right, I think, and probably a breaking change. Here are some notes for discussion and to make sure I don't forget anything:

There are several considerations to think about here. Basically by definition, we want to exclude the setup routine from measurement, so for benchmarks that require a setup we need to generate one or more setup values. Ideally, we actually want to generate one setup value ahead of time for each iteration of the benchmark loop, to minimize measurement overhead. However, if the setup values take up a lot of memory or some other scarce resource, that limits how many of them we can have at once. This is currently a problem with the `iter_with_large_setup` method - since the user is not in control of the number of setup values it generates, it can cause out-of-memory errors. Another problem is raised by the possibility that the setup values (or the values returned by the benchmarked function) implement `Drop` - we probably do not want to include the `drop` function in the benchmark.

So, suppose we have an iteration function that creates a batch of inputs of size N, then calls the benchmark on each of them in a tight loop (measuring the whole batch to reduce measurement overhead). The outputs would be collected into another Vec and batch-dropped outside of the measurement. How should N be determined? If the input is small and holds no external resource, N should be large (or even equal to the iteration count). If the input is large, N should be small enough to ensure that all N inputs (plus all N outputs) can fit in memory. That suggests the user should specify N, but in truth the user probably doesn't really know what N should be either.

Now that I've written all of that out, though, it seems to me that a batched function is a rather neat idea. It has less measurement overhead than `iter_with_setup` and less chance to overflow memory than `iter_with_large_setup`. It could arguably replace `iter_with_large_drop` as well, though it would have marginally more measurement overhead.

The problem of tuning the batch size remains, however. Perhaps this could be mitigated by taking an enum instead of a fixed value - eg. `BatchSize::SmallInput, BatchSize::LargeInput, BatchSize::Specific(usize)` or similar, with documentation to guide the user towards choosing `SmallInput` or `LargeInput` unless they have some specific reason to do otherwise.

EDIT: Any such batched measurement function should have a variant where the benchmark routine accepts the setup input by mutable reference rather than by move. If the setup value implements drop, we probably want to exclude dropping the setup value from the measurements as well, and that may not be possible if the benchmark routine takes the input by value.

EDIT2: As much as possible, there should be a fixed number of batches in each sample. That way, the measurement overhead will be roughly constant regardless of the sample size, which will affect the slope measurements less.

**Comment by LukasKalbertodt** [comment]
Sounds very reasonable! A few comments:

- So far, I solved the "exclude the `drop` from measurement" by returning the value from my main routine so that it is dropped after the measurement. This works, but the problem is that it's easy to forget returning the value. So I guess I agree that you would want to different methods: one where the measurement routine gets the setup by value and one where it gets it by mutable reference (and the latter should be the "default").

- Regarding the "N should be large if the setup values fit into memory": could we run into a caching problem here? If we have a `Vec` of input values that is really big and thus doesn't fit into L3, could that make the measurements include cache misses? Or is that not a problem since we are iterating through the `Vec` sequentially and never have a cache miss?

- And yeah, determining batch size is hard probably. I would agree that we should give the user some control over it. Maybe rather specify an "upper limit", since that's basically what the user cares about: maximal memory usage?

**Comment by LukasKalbertodt** [comment]
@bheisler I just wanted to say "Thank you" again for adding the `iter_batched*` functions. Yesterday I finally got a chance to test them and they are really a nice fit in the library, I think!

**Comment by bheisler** [comment]
Thanks! I'm glad you found it helpful.
