### ISSUE TITLE
Document the meanings of the many levels of benchmark names

### ISSUE THREAD

**Issue by whentze** [bheisler/criterion.rs#288]
There are currently at least 4 levels of naming involved, even when only benching a single function:

1. The name of the benchmark file
2. The name of the benchmark group
3. The name of the benchmark fn
4. The name passed to `Criterion::bench_function` as first parameter.

It is unclear to me from the docs how to give meaningful names to all of these, or even if any of these should just be identical.

**Comment by whentze** [comment]
After trying various combinations, it appears like only 4. is really important. The other don't appear in the report at all.

Even if I make several "benchmark groups", the report does not seem to group them up. What is the intended use for benchmark groups?

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs.

Yes, as you say, the only benchmark names that actually matter are the ones passed to Criterion.rs itself at runtime. I don't want to document that in too much detail since it might change in the near future (at least, if I can find some time to work on this project, anyway) when I get around to building the custom test framework.

The names of the benchmark file and function are not used for anything. The benchmark group is just a name for a macro-generated function that runs all of the benchmarks in that group. The groups are more of a code-organization tool than anything else; they allow a set of benchmarks to share a single `Criterion` object and its associated configuration, and they allow the macro-generated main function to run a group of benchmarks with one call.

**Comment by whentze** [comment]
I see. So I can stop worrying too much about sensible names for benchmark groups etc. Thanks!
