### ISSUE TITLE
Run the same benchmark with different features enabled

### ISSUE THREAD

**Issue by peterjoel** [bheisler/criterion.rs#302]
I would like to benchmark a library that uses features to enable and disable functionality and to compare different implementations, without copy-pasting. For example, I have:
```
#[cfg(cache_padded)]
type Counter = CachePadded<AtomicU64>;
#[cfg(not(cache_padded))]
type Counter = AtomicU64;
```

Is it possible to run the same benchmark for each feature permutation without explicitly passing the feature as `cargo` arguments?

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs.

Sadly, no, this is not possible. It isn't even something I could add, since cargo features happen at compile-time, before any benchmarking code is run.

As an alternative, you could run the benchmarks once with the feature turned off and save a baseline, then run them again with the feature turned on and compare against that baseline. That's kind of a hassle, true,  but you could automate that process with a shell script or similar.

**Comment by peterjoel** [comment]
Thanks @bheisler. I think we can do that. It's just not as nice as having the series all together in one chart for comparison.
