### ISSUE TITLE
Use regex matching to filter benchmarks on the command line

### ISSUE THREAD

**Issue by ggriffiniii** [bheisler/criterion.rs#304]
Sorry if this has been discussed before. I searched the closed issues, but didn't see this topic discussed before. Is there a reason the filtering of benchmarks on program invocation does a simple prefix match rather than a more flexible regex match?

In my case it's pretty limiting.

I have a bunch of benchmarks, but very frequently I will only want to run a subset of the benchmarks to quickly validate if my change had the intended impact.

An example of my situation. I'll have a series of benchmarks that are each comparing two functions and are parameterized over different input sizes.

This leads to benchmarks like

encode_bench/radix64/3
encode_bench/radix64/64
encode_bench/radix64/4096
encode_bench/base64/3
encode_bench/base64/64
encode_bench/base64/4096
encode_with_buffer_bench/radix64/3
encode_with_buffer_bench/radix64/64
encode_with_buffer_bench/radix64/4096
encode_with_buffer_bench/base64/3
encode_with_buffer_bench/base64/64
encode_with_buffer_bench/base64/4096
encode_slice_bench/radix64/3
encode_slice_bench/radix64/64
encode_slice_bench/radix64/4096
encode_slice_bench/base64/3
encode_slice_bench/base64/64
encode_slice_bench/base64/4096
decode_bench/radix64/3
decode_bench/radix64/64
decode_bench/radix64/4096
decode_bench/base64/3
decode_bench/base64/64
decode_bench/base64/4096
decode_with_buffer_bench/radix64/3
decode_with_buffer_bench/radix64/64
decode_with_buffer_bench/radix64/4096
decode_with_buffer_bench/base64/3
decode_with_buffer_bench/base64/64
decode_with_buffer_bench/base64/4096
decode_slice_bench/radix64/3
decode_slice_bench/radix64/64
decode_slice_bench/radix64/4096
decode_slice_bench/base64/3
decode_slice_bench/base64/64
decode_slice_bench/base64/4096

This is a subset of my real benchmark suite, but it's enough to illustrate how regex matching would be more flexible. I could run just radix64 benchmarks, or just the benchmarks on 4096 bytes of input, etc. If you're open to the idea I would be willing to implement it. I haven't looked at the code, but I imagine it would be pretty straightforward.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs.

The benchmark filtering is not a prefix match, but rather a substring match. You should be able to run just the radix64 benchmarks with a filter of "radix64" and the 4096-byte benchmarks with a filter of "4096".

It's true that regexes would provide more flexible filtering than a substring match, but at the cost of adding another crate to Criterion.rs' dependency tree. That means that every developer who uses Criterion.rs needs to pay the costs in terms of download bandwidth and compilation time, and it's not clear to me that the tradeoff is a good one. I'd lean towards not implementing a regex match, but if there's some more user demand for it I could be persuaded otherwise.

**Comment by ggriffiniii** [comment]
Fair enough. Thanks for pointing out it is a substring match. I misspoke and provided bad examples. What prompted me to open the issue was that I frequently wanted to run encode_slice_bench on 4096 bytes of input, I don't know why I changed the examples when opening the issue. Regardless, I can appreciate you wanting to keep the dependency tree minimal, even if it wouldn't be the choice I would make.

**Comment by oconnor663** [comment]
Note from the future: regex support was added in 99de909e381b4239139b15c98bc8b75bd48b76e6 / v0.3.1.
