### ISSUE TITLE
Support larger throughput

### ISSUE THREAD

**Issue by wjhuang2016** [bheisler/criterion.rs#305]
Currently `Throughput` uses `u32` to present `Bytes`. When the throughput is over than 4GB/iteration(limit of `u32`),  the display would be incorrect.
I hope that we can introduce some types like `KiloBytes` or `MegaBytes`.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs and thanks for the suggestion.

I have to admit, the idea that anyone would want more than 4GB/iter hadn't occurred to me. Have you run into a case where you need that? I'd be interested to know what it is.

Now that you mention it, though, I should at least make Throughput non-exaustive in 0.3.0, so that I can potentially add things like this later. Not sure why I didn't do that to start with.

**Comment by bheisler** [comment]
> Now that you mention it, though, I should at least make Throughput non-exaustive in 0.3.0, so that I can potentially add things like this later. Not sure why I didn't do that to start with.

Actually, I just tried to do this and realized that, with the new custom-measurement support in 0.3.0, that doesn't actually make sense. External code will have to match on the Throughput enum and adding a hidden NonExhaustive variant just makes it inconvenient for them to do that. I wouldn't be able to add variants in non-breaking releases anyway, because it would still break custom measurements.

**Comment by wjhuang2016** [comment]
> Hey, thanks for trying Criterion.rs and thanks for the suggestion.
> 
> I have to admit, the idea that anyone would want more than 4GB/iter hadn't occurred to me. Have you run into a case where you need that? I'd be interested to know what it is.
> 
> Now that you mention it, though, I should at least make Throughput non-exaustive in 0.3.0, so that I can potentially add things like this later. Not sure why I didn't do that to start with.

My situation is: reading some data(about 10GB) from disk.

**Comment by bheisler** [comment]
Fair enough. I'll expand it to u64 in 0.3.0, then.

Out of curiosity, how long does each iteration of your benchmark take? 10GB/iter is a lot, so I'm curious what all that data is and why you couldn't have gone with a 1GB dataset.

**Comment by wjhuang2016** [comment]
> Fair enough. I'll expand it to u64 in 0.3.0, then.
> 
> Out of curiosity, how long does each iteration of your benchmark take? 10GB/iter is a lot, so I'm curious what all that data is and why you couldn't have gone with a 1GB dataset.

I want to test the io performance of my database, so I have to write some data bigger than memory.
My ssd is 970pro, and it takes about 10 seconds to read the 10 GB data set sequentially.
