### ISSUE TITLE
Replace gnuplot with plotters(a pure rust crate)?

### ISSUE THREAD

**Issue by Veykril** [bheisler/criterion.rs#313]
I just stumbled upon a pure rust [plotting library](https://github.com/38/plotters) which might be of interest to this project. Since the `criterion-plot` crate is still in need of a maintainer I thought it might be an interesting idea to replace it with this crate instead. It would also remove the need of having `gnuplot` installed to generate plots.

**Comment by bheisler** [comment]
Hey, thanks for the suggestion.

That's great! I didn't know about this library until now. I agree that it would be nice to replace gnuplot with a pure-Rust solution. Unfortunately I'm kinda busy with 0.3.0 and various IRL stuff right now, so this won't be a priority for me, but pull requests would be welcome. If anyone does want to implement this, I'd prefer to add this as an optional Cargo feature and maintain the two backends in parallel, at least for a while, rather than abruptly switching over.

**Comment by 38** [comment]
I am the author of `plotters` crate. I am currently working on the rendering performance for my crate. And `criterion` works perfect for me. But I realized on thing, `criterion` depends on the `gnuplot`. And I have a machine which doesn't have it installed.

This makes me think about using `plotters` to visualize result and I realize there's already a issue. 

So I just tried a quick prototype, the output looks like this: 

![image](https://user-images.githubusercontent.com/3023614/67240215-3f495200-f40e-11e9-8dbd-bff5eb43a373.png)

It's not exactly the same appearance compare to the `gnuplot` generated one. I just wondering if this is acceptable. If yes, I am more than happy to make a PR that allows `criterion` plotting with `plotters` crate. Otherwise, would you mind provide some information about what is missing in the result.

FYI, the change I made for the prototype: https://github.com/38/criterion.rs/commit/1fae1a52e6958d01f5698bd829c060e6719601b1

**Comment by bheisler** [comment]
Hey, thanks for getting in touch. I'm glad that Criterion.rs is working for you.

It doesn't matter too much if the `plotters` charts don't look exactly the same as the `gnuplot` ones. They should be readable and contain the same information. This looks fine to me.

I probably won't get around to implementing it myself any time soon, but a pull request would be welcome.

**Comment by 38** [comment]
Hi, 

I am decide to spend a little time on this task. So before I formal started, I probably need some input from you. 

I think I would like to first refactor code under `src/plot` to make the `criterion_plot` details hide behind a trait object and make `Html` relies on dynamic dispatch for plotting. 

And then I want to make a Plotters backend and make `Html` be able to be instantiated using either criterion_plot or plotters backends. 

Then I think  a command line option can be added to switch backends. By doing so, we can at least having both plotting code for a while and then decide if we want to completely Plotters backend.

If this sounds good to you, I am more than happy to start working on this. But I won't expect I am able to move forward fast, but I can start working on this.

Please let me know if you have any concern about that. And do you have any suggestions on this?

**Comment by bheisler** [comment]
Your plan seems reasonable to me. I don't think I have any particular suggestions to make; using dynamic dispatch makes sense. The code isn't set up for that right now but it should be relatively straightforward to make that change.

The only suggestion that I would make is that there should be a (non-default) Cargo feature to enable compilation of the plotters code. That way, people can opt-in for now without forcing every user of Criterion.rs to pay the compile-time cost of building both backends. If everything goes well, we can make plotters the default backend and have an opt-in for gnuplot in the next breaking-change release.

**Comment by bheisler** [comment]
The PR adding this was merged already, so I'll close this issue.
