### ISSUE TITLE
even all functions in criterion::Criterion consumes "self"

### ISSUE THREAD

**Issue by chuigda** [bheisler/criterion.rs#314]
Of course this may be the elegant API: consume self and return a new one. But in this way, it is impossible to call these functions in benchmarks since the Criterion is borrowed instead of moved.

![图片](https://user-images.githubusercontent.com/29348140/62994780-42fdad00-be90-11e9-8744-623b87b9c088.png)

![图片](https://user-images.githubusercontent.com/29348140/62994796-4db84200-be90-11e9-8073-cd22e68421f0.png)

![图片](https://user-images.githubusercontent.com/29348140/62995012-5cebbf80-be91-11e9-9d2b-3992aa989ca0.png)

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs!

You're not supposed to be able to change the settings on the Criterion object inside a benchmark, that's why it takes `self`. Modifying the Criterion object mid-benchmark could produce some very confusing effects where one benchmark can interfere with another - but only sometimes, with no apparent rhyme or reason, because Criterion.rs sometimes creates new Criterion objects behind the scenes.

For clarity, if you want to change the default configuration on the Criterion object itself you need to provide a function that constructs and returns it to the `criterion_group!` macro. If you want to override the defaults for one specific benchmark (or group of related benchmarks), you'll need to use a `Benchmark` or `ParameterizedBenchmark` object in 0.2.\*, or a `BenchmarkGroup` in 0.3.\* (which is not yet released).

Hope this helps!

**Comment by chuigda** [comment]
This really helps, thank you. I suggest adding this to the documentation.
