### ISSUE TITLE
What exactly does the warm up phase?

### ISSUE THREAD

**Issue by Tockra** [bheisler/criterion.rs#317]
Hello,

I want to use the criterion crate to measure the runtime of my data structure and compare it with other simmilar data structures.

So I want to compare some method calls. 

Now I want to clear the Caches before I want to measure the speed of the method. One of both data structures benefits a lot of from the cache. But in real world there are only cache hits when you called the method or a simmilar method before. 
So I don't want to have data in cache when I measure the runtime of these method and compare it with the second data structure.

What exactly does the "warm up" time do? Does it clear the cache or does it fill the cache so I get more Cache hits (the opossit of my intention)?

T

**Comment by bheisler** [comment]
Hi! Thanks for considering Criterion.rs. The warm-up phase fills caches and does not clear them. Even if you disabled the warm-up, the measurement phase runs the benchmarked function many times and it's likely the caches would be filled quickly.

If you really want to incur frequent cache misses, I would recommend using the `iter_batched` or `iter_batched_ref` timing loops; this would allow you to set up many instances of your data structure in memory and perform the benchmark over all of them. That way, it's more likely that each iteration will need to access a different part of memory, and therefore cause a cache miss. (I assume you're talking about the processor caches here; if your data structures do their own in-memory caching, then `iter_batched`/`iter_batched_ref` are still the way to go because they'll discard the data structures after one method call).

Hope this helps!

**Comment by Tockra** [comment]
Okay thank you for your response. I would change the sample_size, so I need to use the `batch`-method. 
What would be the right syntax for these function to use it as `iter_batched`-method?

**Comment by bheisler** [comment]
There's an example in the API documentation (click the + next to `iter_batched` to expand).

https://bheisler.github.io/criterion.rs/criterion/struct.Bencher.html#method.iter_batched

**Comment by Tockra** [comment]
Like this? :
```rust
        c.bench(id,ParameterizedBenchmark::new(id,move
            |b: &mut Bencher, elems: &Vec<E>| {
                b.iter_batched(|| cache_clear() , |_| {
                    // Laufzeit der For-Schleife wird mitgemessen.
                    for elem in elems {
                        data_structure.predecessor(*elem);
                    }
                }, BatchSize::SmallInput);
            },
            vec![cp]
        ).sample_size(SAMPLE_SIZE));
```
