### ISSUE TITLE
Exporting the results of analysis in machine-readable form

### ISSUE THREAD

**Issue by arazabishov** [bheisler/criterion.rs#332]
First of all, thanks a bunch for an awesome work! 

As stated in the docs:
> The results of Criterion.rs' analysis of these measurements are not currently available in machine-readable form. If you need access to this information, please raise an issue describing your use case.

The use case for me is to plot analysis results in a tex document. I want to combine results of several benchmarks within a single plot using pgfplots, and at the moment I have to retrieve values from the HTML report one by one, which is tedious when you are comparing a bunch of functions. 

For my particular use case, it would be enough to export data points used for the line comparison plot of Criterion into a csv file for example. 

I understand that only my use case can be insufficient for introducing the feature, so I also would be fine if you could point me where I could hack it in as a temp solution :) 

Thanks!

**Comment by bheisler** [comment]
Hey, thanks for the suggestion, and thanks for your patience.

So, as a one-off thing, you can actually dump out the `gnuplot` script Criterion.rs uses to generate that plot by [enabling debug output](https://bheisler.github.io/criterion.rs/book/index.html#debug-output). It's not super great since it actually embeds the output data as binary floating point into an otherwise text-based script file, but it's something. I'm honestly not totally sure how the float arrays are organized in that file, so it might take some reverse-engineering.

If you're OK with just hacking up Criterion.rs to dump out the data you need, you could probably do that in `src/plot/summary.rs:line_comparison` or whichever function generates the plot you want the data for. You could maybe even just modify the code to generate the plot that you ultimately want, but that might take some more work.

I would like to provide machine access to the analyses eventually but that requires a lot of design work for all the new API surfaces it would create.

**Comment by arazabishov** [comment]
Thanks for the response! I found another workaround for collecting mean values and aggregating them into a csv file by scraping the HTML report :) It worked out for me because data available in the HTML report was sufficient in my case.

**Comment by bheisler** [comment]
Sorry, mis-typed the issue number.
