### ISSUE TITLE
Benchmarking Multi-threaded Code

### ISSUE THREAD

**Issue by oliver-giersch** [bheisler/criterion.rs#343]
I am trying to benchmark some multi-threaded code and want to perform all measurements within the threads themselves, so as not to measure the thread spawning overhead.
I found another issue in which the suggested solution was to use the `iter_custom` method.

I came up with the following basic benchmark structure:
```rust
pub fn bench_threads(c: &mut Criterion) {
  c.bench_function("multi-threaded", |b| {
    b.iter_custom(|iters| {
      let mut res = Duration::from_secs(0);
      for _ in 0..iters {
        let mut durations: Vec<Duration> = (0..THREADS)
          .map(|id| { /** spawn thread, perform measurement internally, return duration */ })
          .collect()
          .into_iter().map(|handle| handle.join().unwrap()).collect(); // join threads, collect durations
        // calculate median thread duration
        durations.sort_unstable();
        res += durations[durations.len() / 2];
      }

      res
    });
  });
}
```

Since each thread returns its own measurement and the `iter_custom` closure expects a `Duration` return value, I somewhat arbitrarily return the median value of all measurements in each iteration.

Is the way to go or is there a superior alternative?

**Comment by gz** [comment]
It depends on what you're benchmarking. Median might be fine or you might miss something important (e.g., it could be that your code is favoring 10 out of 12 benchmark threads that end up completing much faster). 
When doing multi-threaded tests, I usually expect all threads to have approximately the same runtime and I synchronize the start of the measurements with a barrier. Then I compare the min/max runtimes from all the threads and if they're not within something like 5-10% of each other, I just do a panic and report it as a 'fairness violation'.

**Comment by bheisler** [comment]
Hey, thanks for the question.

I think the question here is what exactly you're looking to measure. Median is a good way to ignore outliers and get a "typical" value, but sometimes you want to know max time, or min time, or the sum of CPU time across all threads. Which one you choose depends a lot on the specifics of your use-case. For example, in a real-time environment such as game programming, you care more about the maximum time - you want to make sure you'll never drop a frame. On the other hand, in a cluster-computing situation you might care about total time over all threads to that you know how many CPUs you need.

I don't think I can really answer that for you, which is why I designed `iter_custom` so that benchmark author would have to make that decision.

**Comment by oliver-giersch** [comment]
Thanks for the clarification,
I thought there might be a way for letting the framework do the decision about how to best aggregate the individual measurements, but I get that it is supposed to be custom.

Is it correct though to add up the (median in my case) measurements of each iteration and return the total sum?

**Comment by bheisler** [comment]
Yes, if the median is what you want that seems reasonable to me.
