### ISSUE TITLE
Using latest `rayon`, fails the build

### ISSUE THREAD

**Issue by dineshadepu** [bheisler/criterion.rs#352]
Hi,

I am using latest rayon from git. By adding the `criterion` to my dependencies, cargo is not building the project. Here is the error,

```
|  DESKTOP DESKTOP=> cargo test
    Updating crates.io index
error: multiple packages link to native library `rayon-core`, but a native library can be linked only once

package `rayon-core v1.6.0 (/home/dinesh/phd/rusting/rayon/rayon-core)`
    ... which is depended on by `rayon v1.2.0 (/home/dinesh/phd/rusting/rayon)`
    ... which is depended on by `continuous_dem v0.1.0 (/home/dinesh/phd/papers/tpb_sand_stone/src/continuous_dem)`
links to native library `rayon-core`

package `rayon-core v1.4.0`
    ... which is depended on by `rayon v1.0.3`
    ... which is depended on by `criterion v0.2.10`
    ... which is depended on by `continuous_dem v0.1.0 (/home/dinesh/phd/papers/tpb_sand_stone/src/continuous_dem)`
also links to native library `rayon-core`
 
 
```

**Comment by dineshadepu** [comment]
Here is my `toml` file

```
[package]
name = "continuous_dem"
version = "0.1.0"
authors = ["dineshadepu <adepu.dinesh.a@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = { path = "../../../../rusting/rayon"}
neighbours_rs = {path = "../../../../rusting/neighbours_rs"}
simple_shapes = {path = "../../../../rusting/simple_shapes"}
multiphysics_rs = {path = "../../../../rusting/multiphysics_rs"}
cgmath = "0.17.0"
indicatif = "0.12"
rand = "0.7.2"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "struct_copying"
harness = false
```

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs.

So the actual problem here is that Criterion.rs and your library want to use different versions of Rayon. Most of the time that works just fine (Cargo can compile multiple different versions of a library together) but in some cases it doesn't work. One of those cases is when a library links to a C package like `rayon-core` does.

My first suggestion would be to update to Criterion.rs 0.3.0 if possible. That may or may not solve the problem, I'm not sure. That should cause Cargo to use Rayon 1.2.0 for both Criterion.rs and your code, and 1.2.0 should be compatible with Criterion.rs 0.3.0.

If that doesn't help, let me know and I'll try to think of something else.

**Comment by dineshadepu** [comment]
Yeah. I tried updating my `criterion` version, as you mentioned it didn't run. So I cloned both the repos, and using them locally through paths.

**Comment by lemmih** [comment]
Hi @dineshadepu. Another solution would be to patch criterion's dependency:
```
# Add this to your Cargo.toml.
[patch.crates-io]
rayon = { path = "../../../../rusting/rayon"}
```
More documentation here: https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html

If your problem hasn't been resolved, feel free to re-open this issue.
