### ISSUE TITLE
async await support

### ISSUE THREAD

**Issue by quininer** [bheisler/criterion.rs#363]
async/await is stable, and it would be nice if the creterion had first-class support for async/await.

**Comment by bheisler** [comment]
Hey, thanks for the suggestion.

Could you elaborate a bit on what you think "first-class" support would look like?

**Comment by quininer** [comment]
I hope can simply pass future into criterion, like

```rust
b.iter(async {
    foo().await;
});
```

This can be a bit complicated. for simple functions we can use `futures-executor`, but if it involves IO, then we need a runtime like `tokio` and `async-std`.

**Comment by bheisler** [comment]
I don't think it makes sense to have support in Criterion.rs for this. The only way for Criterion.rs to 'benchmark' a future is to run it to completion on some sort of executor. The performance of the executor will affect the performance of the future, so for accurate measurements the executor should be the same one as you'll use in production (or something like `futures::block_on`). For futures that do IO, you're basically required to use either `async-std`'s or `tokio`s executor.

What this means is that the benchmark author is the one who needs to decide which executor to use, not Criterion.rs. I suppose I could expose some option that users could use to configure an executor, but it doesn't seem like that would be significantly better than just requiring the user to call some equivalent of `futures::block_on` which is suitable for their chosen executor.

I'm open to being convinced otherwise, though.

**Comment by 0x8f701** [comment]
@bheisler However if we use `block_on` in `b.iter`, it will always create a thread, we'll never be able to know the real benchmark value...

The importance is to use only one executor for all the test.
```rust
b.iter_async(async { ....  })
```

so an async code executor needs to be added
