### ISSUE TITLE
Most command line options don't work

### ISSUE THREAD

**Issue by TomGillen** [bheisler/criterion.rs#408]
Tested using criterion 0.3.1.

Most command line options are not recognised. For example:

```
cargo bench -- --noplot
```
Produces:
```
    Finished bench [optimized] target(s) in 0.31s
     Running target\release\deps\foo-43f209d680b67c25.exe
error: Unrecognized option: 'noplot'
error: bench failed
```

The same is true for `--baseline`, `--save-baseline` and `--load-baseline`.

`--color never` _does_ work, as does filtering.

**Comment by Terr** [comment]
I'm seeing the same thing with `--sample-size` and `--warm-up-time` in v0.3.2.

Edit: never mind, it seems to be a common issue that is mentioned in the [FAQ](https://github.com/bheisler/criterion.rs/blob/master/book/src/faq.md). Run your benchmarks like so to have Cargo accept everything: `cargo bench --bench $benchmark_name -- --sample-size 10`

**Comment by bheisler** [comment]
Thanks for trying Criterion.rs!

Yes, the problem is that you're (unintentionally) passing arguments that only Criterion.rs understands to both Criterion.rs and libtest benchmarks. Even if you don't think you have any libtest benchmarks, Cargo sneakily runs the test executable compiled from your library crate because it _might_ contain libtest benchmarks, and you have to tell it not to do that. See the [User Guide](https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options) for details on how.
