### ISSUE TITLE
Support for Result<(), E> returning benchmarks

### ISSUE THREAD

**Issue by rbtcollins** [bheisler/criterion.rs#411]
It's obviously possible to wrap all code in an error-unwrapping layer, but the ergonomics of `criterion_group()` and `criterion_main()` would be nicer if they handled that themselves (or perhaps had matching variants).

Reasoning: to bench some of the things I want to bench, I need to call fallible functions, which means sugaring unwrap throughout, or using ? and returning Result<>. The latter is easier to read.

**Comment by bheisler** [comment]
Hey, thanks for the suggestion and thanks for trying Criterion.rs.

I'm not sure I understand what the problem is with the current API. Could you give an example to demonstrate this problem?

**Comment by rbtcollins** [comment]
If my bench functions are defined to return `Result<>`, the criterion_group macro emits this warning:
```
cargo bench --no-run
   Compiling unleash-api-client v0.1.0 (/home/robertc/src/unleash-client-rust)
warning: unused `std::result::Result` that must be used
   --> benches/is_enabled.rs:167:1
    |
167 | criterion_group!(benches, single_call, batch);
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_must_use)]` on by default
    = note: this `Result` may be an `Err` variant, which should be handled
    = note: this warning originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

    Finished bench [optimized] target(s) in 9.52s
```

It would be a convenience to be able to use `Result<>` rather than `unwrap()`, in the same way that `main()` has grown to support it and `#[test]` has as well.

**Comment by bheisler** [comment]
Sorry, I was unclear - can you give an example of a benchmark that triggers this problem?

**Comment by rbtcollins** [comment]
This is the patch that converted from rustc's Bench to Criterion in a project and had bench functions reuturning Result<> https://github.com/cognitedata/unleash-client-rust/commit/7c79a74a198468f027764718bfe0f798e805fa70

so it gives a bit of a before and after feel.

I don't have any actual benchmark /with/ the problem, because an unhandled Result is unsafe code, so I rewrote it when I saw that lint.

**Comment by bheisler** [comment]
Okay, it's not that the code you're benchmarking is fallible (which is allowed already without warning) but that some part of your _setup_ could fail. I would honestly recommend unwrapping in that case. It seems to me that deciding what should happen when the setup fails should be the programmer's responsibility, not Criterion.rs? I could be convinced otherwise though. The only thing that Criterion.rs could do here is drop the result anyway, because if I changed the macros to do anything else then it wouldn't compile for any other return type. Unfortunately I can't invoke the compiler magic that allows `#[test]` and `main` to return different types.

**Comment by bheisler** [comment]
Side note: If I'm reading the code correctly, `bencher` won't compile with group-functions that return values. I guess that `#[bench]` also uses compiler magic to allow returning results.

**Comment by rbtcollins** [comment]
I haven't looked closely enough into procedural macros to offer implementation advice. I do know that things like #async_std::main allow one to either have 
`main()`
or 
`main() -> Result(...)` (subject to some constraints on the E type), so it is definitely doable from that type of structure.

mmm, I'm not suggesting it become Criterion.rs's responsibility - after all ? is just .into() on the E type - but it is pithier code : all I'd be asking Criterion to do is to have a different generated function signature for the main() (or whatever is in the macro's output) that it's macro is creating.

One way it could do that I guess is to have a second ?-friendly variant of the macro?

**Comment by bheisler** [comment]
Thanks again for the suggestion but I don't think this makes sense to add to Criterion.rs.

**Comment by commonsensesoftware** [comment]
Sorry to comment on a closed issue. I would like request _reconsidering_ the final decision. Supporting `Result` in tests has been supported since Rust 2018. It would be _convenient_ to author a benchmark just as idiomatically as any 'ol run-of-the-mill test case.

https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html#tests-and-

The _ask_ here is to be able to author a benchmark using idiomatic syntax and have it _just work_ (like a `#[test]`). For example:

```rust
fn run_benchmark(c: &mut Criterion) -> Result<(), String> {
    c.bench_function("fallible benchmark", |b| {b.iter(|| Bench::run()?}));
}
```

**Comment by erikschul** [comment]
I was surprised by this as well.
The simple workaround is
```

fn criterion_benchmark(c: &mut Criterion) {
    fn inner(c: &mut Criterion) -> Result<()> {
        // ...
        Ok(())
    }
    inner(c).expect("Error in inner.")
}
```
