### ISSUE TITLE
Start at 0 at the origin

### ISSUE THREAD

**Issue by Ekleog** [bheisler/criterion.rs#413]
Hello,

I've started using criterion recently, it looks really great!

This being said, there's something I just noticed, and that surprised me: it looks like violin plots (with plotter) start not at 0, but at the lowest time taken for a run. Which means that the intuitive way to look at it is the wrong one, as things that appear very different may actually be very close.

Would it make sense to have the violin plots in the HTML report have their origin set to zero?

**Comment by Ekleog** [comment]
Thank you!

**Comment by nixpulvis** [comment]
I'm not sure I always agree with this. While it is a common way to "lie with statistics", if you want to actually make use of the information in the violin's distributions, as it gets too far from 0 it collapses into a vertical line and becomes hard to read. At that point a bar graph would be much better.

<img width="887" height="201" alt="Image" src="https://github.com/user-attachments/assets/84675faf-3457-456f-a69e-eb07fb87c305" />

Personally, I'd like to revert this behavior, or configure it.

**Comment by nixpulvis** [comment]
I suppose a different solution to my problem would just to improve the visibility of the violins when they get too narrow, since I'll have this issue even if this behavior was reverted.

<img width="927" height="341" alt="Image" src="https://github.com/user-attachments/assets/ae0f1744-6810-4fe2-835e-5eb02a8ba55f" />
