### ISSUE TITLE
error: bench failed

### ISSUE THREAD

**Issue by abhijeetbhagat** [bheisler/criterion.rs#429]
I am using version `0.3.3` and getting the same `bench failed` error mentioned in #121 
My rust version is -
```
nightly-x86_64-pc-windows-msvc (default)
rustc 1.46.0-nightly (feb3536eb 2020-06-09)
```
Error -
```
Gnuplot not found, using plotters backend
foo                     time:   [0.0000 ps 0.0000 ps 0.0000 ps]
                        change: [-61.959% -1.8275% +165.00%] (p = 0.97 > 0.05)
                        No change in performance detected.
Found 12 outliers among 100 measurements (12.00%)
  4 (4.00%) high mild
  8 (8.00%) high severe
thread 'main' panicked at 'assertion failed: slice.len() > 1 && slice.iter().all(|x| !x.is_nan())', C:\Users\abhi\.cargo\registry\src\github.com-1ecc629
9db9ec823\criterion-0.3.3\src\stats\univariate\sample.rs:29:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: bench failed
```

Bench -
```
use criterion::{black_box, criterion_group, criterion_main, Criterion};

fn bar() {
    let mut a = 10;
    for _ in 0..10 {
        a += 1;
    }
}

fn foo(c: &mut Criterion) {
    c.bench_function("foo", move |b| b.iter(|| bar()));
}

criterion_group!(benches, foo);
criterion_main!(benches);
```

**Comment by bheisler** [comment]
Hey, thanks for the bug report!

Criterion.rs should definitely not fail when this happens.

However, this isn't really benchmarking anything; the whole call to the `bar` function will probably be eliminated by the compiler since it has no observable effects, which might mean the timing loop also gets removed entirely.

Of course, none of the statistical analysis make any sense if the function takes zero time, so it might have to just print a clearer error message instead of panicking.

**Comment by abhijeetbhagat** [comment]
I actually wrote a benchmark first for my module that does IO (parallel parsing of an mmapped MP4 file) but got the same error result. Thinking if the failure had anything to do with my module, I removed the benchmark and wrote the above toy benchmark just to check if there was something wrong with criterion.

**Comment by abhijeetbhagat** [comment]
I just `cargo clean`ed and ran the bench again. It's worked this time. Also, i tried benching my module and it's working too! Not sure  what caused the problem in the first place. Closing this as a result.
