### ISSUE TITLE
Reducing dependency load

### ISSUE THREAD

**Issue by benesch** [bheisler/criterion.rs#457]
I noticed work has started on moving a lot of the plotting/parsing logic to [cargo-criterion](https://github.com/bheisler/cargo-criterion). I'm very excited about this, because, if I understand correctly, this will mean that criterion-the-library can be much lighter weight, and only folks who want to actually run the benchmark will have to acquire the heavyweight dependencies. 

So my question is: can I help? @bheisler, would you appreciate PRs that optionalized the features of criterion-the-library that aren't required when using `cargo-criterion`?

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion!

Yes, that's about correct. The main thing holding it up is just that I haven't gotten around to doing the work. I don't want to move functionality into an optional feature (even if it's enabled by default) without a breaking change release so that has to wait for 0.4.0. I believe I will have more time to work on Criterion in the near future though, so hopefully it won't take too much longer.

Thank you for the offer of assistance, but I don't think I need help on this. The plan in #426 still holds.

**Comment by benesch** [comment]
> Thank you for the offer of assistance, but I don't think I need help on this. The plan in #426 still holds.

Thanks very much for getting back to me. I didn't notice the writeup in #426, sorry! That would have answered most of my questions.

Perhaps there are other ways I can assist though. I (and possibly my employer, @MaterializeInc) would be up for a small monthly contribution, if you've got any interest in setting up GitHub sponsors.

**Comment by bheisler** [comment]
Thanks for the offer, but I don't accept money for my work on Criterion.rs.
