### ISSUE TITLE
How to "unit benchmark"?

### ISSUE THREAD

**Issue by JakkuSakura** [bheisler/criterion.rs#472]
I have a bunch of unit tests. I would like to convert them into benchmarks so I can improve my program speedwise statistically. 

I found a few methods to do this.
1. Copy and paste all unit tests into benches/my_unit_bench.rs. However, it requires all testee to be public
2. Call unit tests from my_unit_bench, with an feature to both keep release mode and access unit tests.

The second solution is by far the most convenient one. Is there an idiomatic way to "unit benchmark"?

Note: `#[cfg_attr(not(feature = "unit_bench"), test)] pub fn some_test()` may help.

**Comment by bheisler** [comment]
Hello! Thanks for your patience.

Sadly, because of the way crates and benchmarks are compiled this is simply not possible to do with Criterion.rs. This isn't something I can fix, either, it would have to be changed at the Cargo/rustc level and would probably cause other problems (though I have recently been in contact with the Cargo team about this issue, I can't promise anything will ever happen as a result).

Although I would point out that unit tests probably don't make good benchmarks.

My recommendation would be to expose the things you want to benchmark to the benchmarks and then write benchmarks to measure exactly what you want to measure rather than whatever your unit tests happen to test.
