### ISSUE TITLE
Benchmark crashing when squaring rug Integers

### ISSUE THREAD

**Issue by olivereanderson** [bheisler/criterion.rs#480]
The following [benchmark](https://github.com/olivereanderson/u128_vs_rug_integer_benchmarks/blob/main/benches/square.rs) crashes on the final value with the following error message: 
`Benchmarking square/square rug::Integer/9223372036854775815: Warming up for 3.0000 serror: process didn't exit successfully`

The following [unit test](https://github.com/olivereanderson/u128_vs_rug_integer_benchmarks/blob/main/src/lib.rs) works without problems, hence I believe there must be a bug in criterion. 

Please let me know how/if I can assist with finding the cause of this bug.

**Comment by bheisler** [comment]
Hello! Thanks for the report, and thanks for your patience.

I believe that this benchmark is causing an out-of-memory error in rug. The way you've structured this benchmark, one value will be squared many times. That will cause it to grow with every iteration of the benchmark. Your unit test only squares the value once.

In addition to making the benchmark run out of memory, this is not a useful benchmark because the amount of work done on each iteration increases with each iteration.

I would recommend using a benchmark like this instead (just written from memory, may not compile):

```
group.bench_with_input(
    BenchmarkId::new("square rug::Integer", format!("{}", input)),
    &input,
    |b, input| {
        // Use iter_batched to create a new Integer for each iteration
        b.iter_batched(
            || Integer::from(input.clone()),
            |value| {
                // Remove the ; here to return the Integer, to avoid including the drop time in the measurement
                Integer::from(value.square_ref()) measurement
            },
            BatchSize::SmallInput,
        )
    },
);
```
