### ISSUE TITLE
'there is no reactor running, must be called from the context of a Tokio 1.x runtime'

### ISSUE THREAD

**Issue by CalebEverett** [bheisler/criterion.rs#536]
I ended up thinking this might be an an issue. I was following the example in the docs, but am still getting this error:

'there is no reactor running, must be called from the context of a Tokio 1.x runtime'

If I just don't call the async function inside `create_data_items` it works fine.

```rust
async fn create_data_items(temp_dir: &TempDir) -> Result<(), Error> {
...
    let _ = arweave
        .create_data_items_from_file_paths(paths_iter, Vec::new())
        .await?;
    Ok(())
}
fn from_elem(c: &mut Criterion) {
    let mut group = c.benchmark_group("from_elem");
    for (size, num_files) in [(10, 10usize), (15, 10)]
        .iter()
        .map(|(s, f)| (usize::pow(2, *s), f))
    {
        let temp_dir = files_setup(size.clone(), num_files.clone()).unwrap();
        group.throughput(Throughput::Bytes(size as u64));
        group.bench_with_input(BenchmarkId::new("input_example", size), &size, |b, &s| {
            b.to_async(FuturesExecutor)
                .iter(|| create_data_items(&temp_dir));
        });
    }
}
```

**Comment by bheisler** [comment]
Hello! In order to run an async function, you need some sort of executor or runtime. Simple futures don't care which runtime you run them in, but tokio's async IO functionality depends on a tokio runtime and breaks when run in any other executor. Criterion.rs has support for several widely-used async executors and additional ones can be plugged in as needed.

Your code uses tokio's async IO so it needs to run in a tokio runtime, but you've passed a FuturesExecutor to `to_async`. That specifies that the future should be executed by the `futures` crate's simple current-thread executor rather than a tokio runtime. The FuturesExecutor is the simplest one to use so that's what I put in the examples, but you'll need to pass a `tokio::runtime::Runtime` (or reference to same) so that your futures are run on the correct executor.

Hope this helps!

**Comment by CalebEverett** [comment]
Thank you - I think I can figure that out.
