### ISSUE TITLE
Can not find gnuplot 5.4 on Windows

### ISSUE THREAD

**Issue by jinq0123** [bheisler/criterion.rs#570]
`cargo bench` reports:
```
Gnuplot not found or not usable, using plotters backend
`gnuplot --version` returned an unparseable version string:
```

gnuplot 5.4 is installed:
```
>gnuplot --version
gnuplot 5.4 patchlevel 3
```

I found gnuplot version was not piped as expected.
```
>gnuplot --version > out.txt
```
out.txt is empty.

I installed gnuplot 5.2.8 to walk around this.

**Comment by jonny-im** [comment]
I have the same problem. I Gnuplot 5.4 patchlevel 3 installed also get the  same error:

```
Gnuplot not found or not usable, using plotters backend
`gnuplot --version` returned an unparseable version string: 
```

**Comment by BuyMyMojo** [comment]
Still same issue error with `gnuplot 5.5 patchlevel 0`

**Comment by bheisler** [comment]
Hello! Thanks for the bug report.

I haven't been able to reproduce this issue with `gnuplot 5.4 patchlevel 4`.

For those of you having this issue, can you check if gnuplot is maybe printing its output to stderr?

**Comment by BuyMyMojo** [comment]
```bash
$ gnuplot.exe

        G N U P L O T
        Version 5.5 patchlevel 0    last modified 2022-08-10

        Copyright (C) 1986-1993, 1998, 2004, 2007-2022
        Thomas Williams, Colin Kelley and many others

        gnuplot home:     http://www.gnuplot.info
        mailing list:     gnuplot-beta@lists.sourceforge.net
        faq, bugs, etc:   type "help FAQ"
        immediate help:   type "help"  (plot window: hit 'h')

Terminal type is now 'qt'
Encoding set to 'cp1252'.
gnuplot>
```

**Comment by BuyMyMojo** [comment]
Sorry I misread, whe nrunning cargo bench it does not output to the terminal, I get an error of it being unparsable
```bash
`gnuplot --version` returned an unparseable version string: gnuplot 5.5 patchlevel 0
```

**Comment by bheisler** [comment]
Well, what I wanted to know is whether `gnuplot --version` prints its version to stderr or stdout.

**Comment by grtwje** [comment]
Works for me, Windows 11 and gnuplot 5.4 patchlevel 6.  Likely not helpful to those with the problem, but it is a reference data point.

**Comment by hecatia-elegua** [comment]
win10 gnuplot 5.4 patchlevel 6,
another data point:
1. make sure gnuplot/bin is in PATH
2. restart vscode
3. use `cargo bench -- --plotting-backend gnuplot`
4. returns "`gnuplot --version` returned an unparseable version string"
5. restart vscode
6. use `gnuplot --version`
7. works
8. use `cargo bench -- --plotting-backend gnuplot`
9. works

**Comment by sandersaares** [comment]
`gnuplot --version` returned an unparseable version string: gnuplot 6.1 patchlevel 0

The version string is in the error message, so it has to be in stdout because `parse_version()` did get a correct-seeming string. If I copy-paste this same string from the error message and smash it into `parse_version()`, everything works fine. This suggests the problem is something we cannot see.

![image](https://github.com/bheisler/criterion.rs/assets/9914262/efc767b1-930c-4fd7-b372-5d4db56e835c)

Oh hey, that is not UTF-8 that gnuplot is emitting, it is UTF-16! Feeding that into `String::from_utf8()` is not going to result in happy times.

Why does it show up fine in the error message then? I suppose something somewhere along the pipeline to the error getting printed just skips the 0x00 bytes when displaying.

If all that Criterion needs here is detect version, perhaps a "try again with UTF-16 just in case" fallback might be useful?
