### ISSUE TITLE
Maybe log repeated benchmark IDs?

### ISSUE THREAD

**Issue by chetmurthy** [bheisler/criterion.rs#589]
I recently made the mistake of repeating a benchmark ID, and got a cryptic assert failure.  I thought: maybe it'd be nice if there were an error-message, telling me what repeated ID was.  If this is OK with you, I can rapidly send you a PR.  Just wanna check that this something you'd approve, before doing the bureaucracy.  B/c the code is so trivial, the only work here is in preparing the PR.

```
modified   src/benchmark_group.rs
@@ -288,6 +288,9 @@ impl<'a, M: Measurement> BenchmarkGroup<'a, M> {
             self.throughput.clone(),
         );
 
+        if self.all_ids.contains(&id) {
+            println!("Error: repeated benchmark id {}", id) ;
+        }
         assert!(
             !self.all_ids.contains(&id),
             "Benchmark IDs must be unique within a group."
```

**Comment by bheisler** [comment]
Hello! Thanks for the suggestion.

This is actually surprisingly hard to do correctly in Criterion-rs due to a lot of fine details you probably don't care about, which is why it isn't already done.

(Though it's easy to ensure uniqueness within a group - in fact, at the bottom of the code snippet you posted you can see that it is already enforcing exactly that with an assertion. I'm assuming in your case you had something more complex going on, or you would have hit that assertion.)

However, those reasons don't apply to `cargo-criterion` and so it does already handle duplicate IDs more gracefully than Criterion-rs itself can. I would encourage you to use `cargo-criterion` instead of `cargo bench` to run your benchmarks - the long-term plan is for that to be the primary way to run Criterion benchmarks anyway.

**Comment by chetmurthy** [comment]
Ah, yes.  I should have noted that, yes indeed, I hit the assertion.  But the assertion doesn't actually tell you which benchmark id was repeated, which was the critically useful bit of info I needed to go change my benchmark configuration.  When you have a bunch of different benchmarks in the group, that's ... pretty useful info to have.

**Comment by bheisler** [comment]
Ah, that is a fair point. I've just changed it to add the duplicated ID to the assertion message.
