### ISSUE TITLE
[ Questions]: Module related questions

### ISSUE THREAD

**Issue by dclong** [bheisler/criterion.rs#594]
1. It seems to me that criterion supports the old way (Rust 2015) of module. When will criterion support the new way of modules (without using `mod.rs`)?

2. When using nested modules, is there any way to add benchmarks of submodules into a super module? Taking benchmarks in this repository as example, is there anyway to add benchmarks of all submodules of the `benchmark` module into `benchmark`, and then in `bench_main.rs` we can just add something like `criterion_main!{ benchmarks::benches }`? I feel this way is more nature and consistent with how the module system works in Rust. 
    <img width="837" alt="image" src="https://user-images.githubusercontent.com/824507/178091589-1a3abf45-6bbe-4203-a95c-79202e81bab1.png">

**Comment by bheisler** [comment]
Hello!

> It seems to me that criterion supports the old way (Rust 2015) of module. When will criterion support the new way of modules (without using mod.rs)?

I admit I'm a bit confused by this. Sure, I've not been actively following Rust's development as much lately, but I don't think they've changed the module syntax on me. Even if they had, I also don't think Criterion-rs would have to do anything to support the new syntax. I use `mod.rs` files in my own code because that's what I'm used to, but they are optional, and Criterion-rs should work just fine either way. The examples in the documentation probably use `mod.rs` - that might be because that's what I'm used to, that might be because I wrote them before `mod.rs` became optional. Either way, Criterion.rs works just fine with or without a `mod.rs` file.

> When using nested modules, is there any way to add benchmarks of submodules into a super module? Taking benchmarks in this repository as example, is there anyway to add benchmarks of all submodules of the benchmark module into benchmark, and then in bench_main.rs we can just add something like criterion_main!{ benchmarks::benches }? I feel this way is more nature and consistent with how the module system works in Rust.

You may be interested in using the [`criterion-macro`](https://crates.io/crates/criterion-macro) crate, which allows you to tag benchmark functions with `#[criterion]` (similar to how you can tag unit tests with `#[test]`) instead. That requires nightly builds of the compiler though because [the RFC](https://github.com/rust-lang/rfcs/blob/master/text/2318-custom-test-frameworks.md) that defined support for them and the implementation of that support in the compiler are both still experimental.

Otherwise, no, there's no way to do that. The existing macros work the way they do because they have to work that way in order to work at all. The custom test framework was supposed to replace those macros but until the Rust core developers stabilize the RFC and commit to an implementation the macros have to stick around.

**Comment by dclong** [comment]
I tried the new style of submodules but it doesn't work. Below is the structure the benches directory in my project. 
```
-- benches
    -- bench_main.rs
    -- pineapple.rs
    -- pineapple/
        -- play.rs
```
The file `pineapple.rs` declare its submodule.
```
pub mod play;
```
See the error message below.
![image](https://user-images.githubusercontent.com/824507/179341278-3b030c36-5ab8-407b-90fa-905565974b85.png)

**Comment by bheisler** [comment]
Sorry, but that would be an issue for rustc, not Criterion.rs, unless I'm badly misunderstanding something.
